clear all,
close all;

dados_salvos = './estatisticas.mat';

load(dados_salvos);

% ############# config para graficos:
fator = 170;
img_w = 5 * fator;
img_h = 3 * fator;
img_ph = 800;
img_pv = 400;
line_w = 1.5;
% ##########################

s = estatisticas;

s.ber = 100 * s.n_err_acc ./ s.n_acc;

% createFit(s.Fs_x_up, s.ber)

%%
% function [fitresult, gof] = createFit(Fs, ber)
    %CREATEFIT(FS,BER)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : Fs
    %      Y Output: ber
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 23-Mar-2022 00:10:35
    
    
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( s.Fs_x_up, s.ber );
    
    % Set up fittype and options.
    % ft = fittype( 'gauss2' );
    % opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    % opts.Display = 'Off';
    % opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
    % opts.StartPoint = [37.2549019607843 21 1.80440090487331 29.4117628573303 13.6 0.709804124530016];
    
    % % Fit model to data.
    % [fitresult, gof] = fit( xData, yData, ft, opts );

    % Set up fittype and options.
    ft = fittype( 'poly3' );
    opts = fitoptions( 'Method', 'LinearLeastSquares' );
    opts.Robust = 'LAR';

    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    
    % Plot fit with data.
    figure('Name', 'BER vs Fs', 'Position', [img_ph img_pv img_w img_h])
    h = plot(xData, yData, '*b' );
    xlabel( 'Taxa de amostragem [amostras/s]', 'Interpreter', 'none' );
    ylabel( 'BER [%]', 'Interpreter', 'none' );
    grid on;
    ylim([-1 40]);
    figure('Name', 'BER vs Fs', 'Position', [img_ph img_pv img_w img_h])
    h = plot( fitresult, xData, yData, '*b' );
    h(2).LineWidth=1.5;
    % hLeg = legend(h);
    % set(hLeg, 'visible', 'off');
    legend( h, 'BER calculada', 'Curva de tendência', 'Location', 'southeast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'Taxa de amostragem [amostras/s]', 'Interpreter', 'none' );
    ylabel( 'BER [%]', 'Interpreter', 'none' );
    grid on;
    ylim([-1 40]);

% end
