%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: E:\Franco\Google Drive\UFES\ENG ELÉTRICA\10º Período\Progeto de Graduação 2\Software\pg2_matlab\F0077CH1.CSV
%
% Auto-generated by MATLAB on 15-Sep-2021 11:52:30

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["RecordLength", "e03", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "double", "string", "double", "double", "string"];
opts = setvaropts(opts, [1, 3, 6], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 4, 5], "DecimalSeparator", ".");
opts = setvaropts(opts, [1, 3, 6], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CH1 = readtable("F0077CH1.CSV", opts);


%% Clear temporary variables
clear opts