function CH1 = importfile(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  CH1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as a table.
    %
    %  CH1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  CH1 = importfile("E:\Franco\Google Drive\UFES\ENG ELÉTRICA\10º Período\Progeto de Graduação 2\Software\pg2_matlab\F0077CH1.CSV", [1, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 15-Sep-2021 11:50:04
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [1, Inf];
    end
    
    %% Setup the Import Options
    opts = delimitedTextImportOptions("NumVariables", 6);
    
    % Specify range and delimiter
    opts.DataLines = [1, Inf];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["RecordLength", "e03", "VarName3", "VarName4", "VarName5", "VarName6"];
    opts.VariableTypes = ["string", "double", "string", "double", "double", "string"];
    opts = setvaropts(opts, [1, 3, 6], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, [2, 4, 5], "DecimalSeparator", ".");
    opts = setvaropts(opts, [1, 3, 6], "EmptyFieldRule", "auto");
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    
    % Import the data
    CH1 = readtable(filename, opts);
    
end